version: '3.5'

volumes: 
  postgres_data_<%= name %>:

networks: 
  postgres_<%= name %>_network:

services:
  <%= name %>:
    image: ${REGISTRY}<%= name %>:latest
    container_name: $COMPOSE_PROJECT_NAME.<%= name %>
    build: 
      context: ./services/<%= name %>
      dockerfile: ./docker/Dockerfile
    networks: 
      - postgres_<%= name %>_network
    volumes: 
      - ./services/<%= name %>/src/initdb:/docker-entrypoint-initdb.d
      - ./services/<%= name %>/docker/postgresql:/etc/postgresql
      - postgres_data_<%= name %>:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
      - POSTGRES_INITDB_WALDIR=${POSTGRES_INITDB_WALDIR}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}