version: "3.5"

networks:
  proxy:
    name: tier_1

services:
  <%= name %>:
    image: ${REGISTRY}<%= name %>:latest
    container_name: ${COMPOSE_PROJECT_NAME}.<%= name %>
    restart: unless-stopped
    build:
      context: ./services/<%= name %>
      dockerfile: ./docker/Dockerfile
      target: ${BUILD_TARGET}
    environment:
      - VIRTUAL_HOST=<%= name %>
    volumes:
      - ./services/<%= name %>/src:/app
    networks:
      - proxy
    stdin_open: true
