version: '3.5'

networks:
    <% if(fpmService || proxyPass) { %><%=fpmService || proxyPass %>_net:<% } %>
    proxy:
        external:
            name: tier_1

<% if(fpmService) { %>
volumes: 
    fpm_share_code:
<% } %>

services:
  <%= name %>:
    image: ${REGISTRY}<%= name %>:latest
    container_name: ${COMPOSE_PROJECT_NAME}.<%= name %>
    restart: unless-stopped
    build: 
        context: ./services/<%= name %>
        dockerfile: ./docker/Dockerfile
    volumes:
        - ./services/<%= name %>/docker/config/fastcgi_params.conf:/etc/nginx/fastcgi_params.conf
        - ./services/<%= name %>/docker/config/mime.types:/etc/nginx/conf/mime.types
        - ./services/<%= name %>/docker/config/nginx.conf:/etc/nginx/nginx.conf
        - ./services/<%= name %>/docker/config/proxy.conf:/etc/nginx/proxy.conf
        <% if(fpmService) {
        %>- fpm_share_code:<%= fpmCodePath %>
        - ./services/<%= fpmService %>/src:<%= fpmCodePath %><% }
        else { %>- ./services/<%= name %>/src:<%= fpmCodePath %><% } %>
    environment: 
        - VIRTUAL_HOST=<%= fpmService || proxyPass %>
    networks:
        - proxy
        <% if(fpmService || proxyPass) { %>- <%= fpmService || proxyPass %>_net<% } %>
    depends_on: 
        - proxy
        - dockergen<% if(fpmService) { %>
        - <%= fpmService %>
        <% } %><% if(proxyPass) { %>
        - <%= proxyPass %>
        <% } %>