version: '3.5'

volumes: 
  mongo_data_<%= name %>:

networks: 
  mongo_<%= name %>_network:

services:
  <%= name %>:
    image: ${REGISTRY}<%= name %>:latest
    container_name: $COMPOSE_PROJECT_NAME.<%= name %>
    restart: unless-stopped
    build: 
      context: ./services/<%= name %>
      dockerfile: ./docker/Dockerfile
    volumes: 
      - ./services/<%= name %>/src/initdb:/docker-entrypoint-initdb.d
      - mongo_data_<%= name %>:/data/db
    networks:
      - mongo_<%= name %>_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}