version: "3.5"

networks:
  proxy:
    name: tier_1

services:
  <%= templateName %>:
    image: ${REGISTRY}<%= templateName %>:latest
    container_name: ${COMPOSE_PROJECT_NAME}.<%= templateName %>
    build:
      context: ./services/<%= templateName %>
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./services/<%= templateName %>/src:/app
    networks:
      - proxy
